[package]
name = "rs_service_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumqttc = { version = "0.24.0", features = ["use-rustls"] }
sparkplug-rs = "0.4.0"
